version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: greg-postgres-dev
    environment:
      POSTGRES_DB: greg_fullstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d greg_fullstack"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - greg-network-dev

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: greg-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - greg-network-dev
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin

volumes:
  postgres_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local

networks:
  greg-network-dev:
    driver: bridge
